"""add feedback table

Revision ID: 570442c67e2b
Revises: 890c189bc26b
Create Date: 2026-09-05 15:21:15.469277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570442c67e2b'
down_revision: Union[str, Sequence[str], None] = '890c189bc26b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('human_action', sa.String(length=20), nullable=False),
    sa.Column('modification_reason', sa.Text(), nullable=True),
    sa.Column('predicted_outcome', sa.Text(), nullable=True),
    sa.Column('actual_outcome', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('outcome_recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['agent_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_id'))

    op.drop_table('feedback')
    # ### end Alembic commands ###
