"""baseline schema

Revision ID: 890c189bc26b
Revises: 
Create Date: 2026-09-01 17:11:49.746729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890c189bc26b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_communication_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_agent_id', sa.String(length=50), nullable=False),
    sa.Column('target_agent_id', sa.String(length=50), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_communication_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_communication_policies_id'), ['id'], unique=False)

    op.create_table('agents',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner', sa.String(length=50), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('human_approval_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=True),
    sa.Column('execution_id', sa.String(length=50), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('resource', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('condition_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('wave_height_m', sa.Float(), nullable=True),
    sa.Column('swell_height_m', sa.Float(), nullable=True),
    sa.Column('wind_wave_height_m', sa.Float(), nullable=True),
    sa.Column('wave_period_s', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('wind_gusts_kmh', sa.Float(), nullable=True),
    sa.Column('wind_direction_deg', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.String(length=40), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('condition_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_condition_readings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_condition_readings_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_condition_readings_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_condition_readings_severity'), ['severity'], unique=False)
        batch_op.create_index('ix_condition_unique_observation', ['location', 'observed_at'], unique=True)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_id'), ['id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('is_implemented', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_id'), ['id'], unique=False)

    op.create_table('risk_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('scoring_method', sa.String(length=20), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_readings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_readings_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_readings_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('risk_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('likelihood', sa.String(length=30), nullable=False),
    sa.Column('impact', sa.String(length=30), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('mitigation_plan', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risks_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OPERATOR', 'SUPERVISOR', 'ADMIN', name='userrole', native_enum=False, length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('agent_capabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=True),
    sa.Column('capability', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_capabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_capabilities_id'), ['id'], unique=False)

    op.create_table('agent_executions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=True),
    sa.Column('parent_execution_id', sa.String(length=50), nullable=True),
    sa.Column('request_id', sa.String(length=50), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('policy_decisions', sa.JSON(), nullable=True),
    sa.Column('approval_status', sa.String(length=30), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_executions_id'), ['id'], unique=False)

    op.create_table('agent_health',
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('failure_rate', sa.Float(), nullable=True),
    sa.Column('average_latency', sa.Float(), nullable=True),
    sa.Column('timeout_count', sa.Integer(), nullable=True),
    sa.Column('policy_violation_count', sa.Integer(), nullable=True),
    sa.Column('denied_actions', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('agent_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=True),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_permissions_id'), ['id'], unique=False)

    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=True),
    sa.Column('execution_id', sa.String(length=50), nullable=True),
    sa.Column('recommendation', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('reviewer_id', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['agent_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_requests_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_requests_id'))

    op.drop_table('approval_requests')
    with op.batch_alter_table('agent_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_permissions_id'))

    op.drop_table('agent_permissions')
    op.drop_table('agent_health')
    with op.batch_alter_table('agent_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_executions_id'))

    op.drop_table('agent_executions')
    with op.batch_alter_table('agent_capabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_capabilities_id'))

    op.drop_table('agent_capabilities')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risks_id'))

    op.drop_table('risks')
    with op.batch_alter_table('risk_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_readings_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_risk_readings_location'))
        batch_op.drop_index(batch_op.f('ix_risk_readings_id'))

    op.drop_table('risk_readings')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_id'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))

    op.drop_table('events')
    with op.batch_alter_table('condition_readings', schema=None) as batch_op:
        batch_op.drop_index('ix_condition_unique_observation')
        batch_op.drop_index(batch_op.f('ix_condition_readings_severity'))
        batch_op.drop_index(batch_op.f('ix_condition_readings_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_condition_readings_location'))
        batch_op.drop_index(batch_op.f('ix_condition_readings_id'))

    op.drop_table('condition_readings')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_type'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_id'))

    op.drop_table('agents')
    with op.batch_alter_table('agent_communication_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_communication_policies_id'))

    op.drop_table('agent_communication_policies')
    # ### end Alembic commands ###
